spring:
  application:
    name: TechDeliver
  datasource:
    url: jdbc:postgresql://localhost:5432/techdeliver
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  graphql:
    path: /graphql
    graphiql:
      enabled: true
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

auth:
  token:
    jwtSecret: 367639792442264529484840635166546457605A7134743777217A2543244620
    expirationInMils: 3600000