
extend type Query {



    getCategoryById(categoryId: ID!): CategoryResponse!

    getCategoryByName(name: String!): CategoryResponse!

    getAllCategories: CategoryListResponse!


}

extend type Mutation {

    createCategory(input: CreateCategoryInput!): CategoryResponse!

}


type CategoryResponse {
    categoryDto: CategoryDto
    message: String!
}

type CategoryListResponse {
    categories: [CategoryDto]
    message: String!
}


type CategoryDto {
    categoryId: ID
    categoryName: String
    categoryDescription: String
    products: [ProductDto]
}

input CreateCategoryInput {
    name: String!
    description: String
}


