
extend type Query {

    getUserOrders(userId: ID!): [OrderDto]

    getAllOrders: [OrderDto]

}

extend type Mutation {

    placeOrder(input: PlaceOrderInput!): OrderDto

    calculateOrderPreview(input: PlaceOrderInput!): OrderInfoDto

    updateOrderStatus(orderId: ID!, status: String!): OrderDto
}

input PlaceOrderInput {
    userId: ID!
    deliveryAddress: String
    deliveryUrgency: String
    distanceInKM: Float
    needInstallation: Boolean
}

type OrderDto {
    id: String
    userId: String

    orderDate: String # TODO:  problem here
    deliveryAddress: String
    distanceInKM: Float

    orderTotalPrice: Float
    orderItemsTotalPrice: Float
    deliveryTotalPrice: Float
    installationPrice: Float

    deliveryUrgency: String
    status: String

    orderItems: [OrderItemDto]
}

type OrderItemDto {
    productId: String
    productName: String
    productBrand: String
    quantity: Int
    price: Float
}

type OrderInfoDto {
    userId: ID
    orderDate: String
    deliveryAddress: String
    orderTotalPrice: Float
    orderItemsTotalPrice: Float
    deliveryTotalPrice: Float
    installationPrice: Float
    orderItems: [CartItemDto]
}

