
extend type Query {

    getUserProfileInfo(userId: ID!): UserDto

    getUserSavedProducts(userId: ID!): [ProductDto]

    getUserDeliveryAddress(userId: ID!): String

    getSavedProductsIds(userId: ID!): [String]

#    getUserDeliveryAddresses(userId: ID!): [String]

    getAllUsers: [UserDto]
}

extend type Mutation {

    updateUsername(userId: ID!, newUsername: String!): UserDto

    updateUserPassword(userId: ID!, oldPass: String!, newPass: String!): UserDto

    setDeliveryAddress(userId: ID!, address: String!): Boolean

    saveProduct(productId: ID!, userId: ID!): ProductDto

    unsaveProduct(productId: ID!, userId: ID!): Boolean

    blockUser(userId: ID!): UserDto
}

type UserDto {
    userId: ID!
    email: String
    username: String
    roles: [String]
    savedDeliveryAddress: String #TODO: rename to activeDeliveryAddress (+ add multiple addresses)
}